# Generated by Django 4.1.1 on 2022-09-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('csid', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cdid', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
