# Generated by Django 4.1.1 on 2022-09-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divelink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsu',
            name='cdid',
        ),
        migrations.RemoveField(
            model_name='rsu',
            name='csid',
        ),
        migrations.AddField(
            model_name='rsu',
            name='activate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rsu',
            name='ldid',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rsu',
            name='lsid',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
