# Generated by Django 4.1.1 on 2022-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divelink', '0002_remove_rsu_cdid_remove_rsu_csid_rsu_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsu',
            name='uid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
