run:
	@python3 manage.py runserver 0.0.0.0:8000 --noreload

migrate:
	@python3 manage.py migrate --run-syncdb

loaddata:
	@python3 manage.py loaddata devicetype.json
	@python3 manage.py loaddata apptype.json

superuser:
	@python3 manage.py createsuperuser

run-celery-worker:
	@celery -A django_graph worker -l info

run-celery-beat:
	@celery -A django_graph beat -l info

run-redis:
	redis-server --daemonize yes